name: CI

on:
  pull_request: 
  push:
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    timeout-minutes: 50
  
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yum -y install epel-release redhat-lsb
        yum -y install python-devel python-dateutil PyYAML wget git flex bison bzip2 rpm-build
        yum -y install libmodbus-devel mosquitto-devel riemann-c-client-devel ganglia-devel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: ./esmon_build
